parameters:
- name: environment
  type: string
- name: appName
  type: string
- name: isPreviousStageSuccessful
  type: boolean

jobs:
- deployment: Deploy
  pool:
    vmImage: 'ubuntu-20.04'
  environment: ${{ parameters.environment }}
  variables:
  - group: 'Release'
  condition: and(succeeded(), eq(variables['isPreviousStageSuccessful'], 'true'))
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: drop
        - task: AzureWebApp@1
          displayName: 'Azure App Service Deploy: website'
          inputs:
            azureSubscription: 'Resource Manager - Tailspin - Space Game'
            appName: ${{ parameters.appName }}
            package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/*.zip'